version: '3'
services:
  app:
    build: .
    container_name: crud-api
    volumes:
      - ./:/home/Crud-api
    ports:
      - "8030:8080"
    depends_on: 
      - db
  db:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: crud-api
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
volumes:
  db_data: {} 